### ISSUE TITLE
Getting 0 results for 1.18.2 world

### ISSUE THREAD

**Issue by Tom3s** [SciCraft/mc-scanner#3]
Running the command `java -jar mc-scanner-0.2.0.jar --stats <world name> <output dir name>` will run fine, and I think it finds the region files, because it outputs 131 messages: `131/131 422.7MiB/422.7MiB 129.5MiB/s 0 results`, but all of them have 0 results and the output files are empty as well

**Comment by Akari202** [comment]
I am getting zero reesults, however it is giving me the error:
```
Error scanning RegionFile(overworld, x=-17, z=13)
java.io.EOFException
	at de.skyrising.mc.scanner.UtilsKt.readFully(utils.kt:23)
	at de.skyrising.mc.scanner.region.RegionReader.accept(io.kt:17)
	at de.skyrising.mc.scanner.RegionFile.scan(region.kt:40)
	at de.skyrising.mc.scanner.ScannerKt.runScan$lambda-7$lambda-6(scanner.kt:177)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
for every reigon file. I assume this is due to the changes in world format in 1.18, the program expects the world to only be 256 blocks tall

**Comment by alide123321** [comment]
im getting the same thing 1.8GiB/1.8GiB 197.0MiB/s 0 results

im on 1.19
