### ISSUE TITLE
Issues scanning 1.21 inventory?

### ISSUE THREAD

**Issue by patrickmacarthur** [SciCraft/mc-scanner#7]
I'm guessing the NBT format changes are causing problems?

```
PS C:\multimc\instances\1.21\.minecraft\saves> java -jar C:\Users\Patrick\Downloads\mc-scanner-0.5.1.jar --stats temp result.zip
[]
Error scanning RegionFile(overworld, x=-1, z=-1)
java.lang.IllegalArgumentException: No int value for Count
        at de.skyrising.mc.scanner.CompoundTag.getInt(nbt.kt:331)
        at de.skyrising.mc.scanner.InventoriesKt.scanInventory(inventories.kt:65)
        at de.skyrising.mc.scanner.RegionKt.scanChunkItems(region.kt:135)
        at de.skyrising.mc.scanner.RegionKt.scanChunk(region.kt:82)
        at de.skyrising.mc.scanner.RegionFile$scan$1$1.invoke(region.kt:43)
        at de.skyrising.mc.scanner.RegionFile$scan$1$1.invoke(region.kt:42)
        at de.skyrising.mc.scanner.region.RegionVisitor$Companion$visitAllChunks$1$visitChunk$1.visit(visitors.kt:21)
        at de.skyrising.mc.scanner.region.RegionReader.visitChunk(io.kt:107)
        at de.skyrising.mc.scanner.region.RegionReader.accept(io.kt:32)
        at de.skyrising.mc.scanner.RegionFile.scan(region.kt:42)
        at de.skyrising.mc.scanner.ScannerKt.runScan$lambda-4$lambda-3(scanner.kt:202)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

5/5 10.1MiB/13.7MiB 38.2MiB/s 0 results
```

I can provide the region file if needed to debug this issue, but I imagine it should be reproducible by creating a new 1.21 world and placing barrels with shulker boxes containing items.

**Comment by M4ximumPizza** [comment]
This is also a issue on my end for 1.21.4.

**Comment by Alzax317** [comment]
I have the same problem
